#### Programming Test

In [1]:
user_sys = {}

def newusers():
    new_name = input('Please enter a name: ')
    while user_sys.get(new_name):
        new_name = input('Please enter a name: ')
    password = input('Please enter your password: ')
    user_sys[new_name] = password

In [2]:
def oldusers():
    name = input('Please enter your name: ')
    password = input('Please enter your password: ')
    if name:
        if user_sys.get(name)==password:
            print(name,' welcome back.')
        else:
            print('login incorrect')
    
def exit():
    pass

In [3]:
def login(x):
    return {
        'N':newusers,
        'O':oldusers,
        'E':exit
    }[x]

In [4]:
login('N')()

Please enter a name: roach
Please enter your password: sinai


In [5]:
newusers()

Please enter a name: roach
Please enter a name: sinai
Please enter your password: sinai


In [6]:
help(dict.copy)

Help on method_descriptor:

copy(...)
    D.copy() -> a shallow copy of D



In [7]:
user_sys

{'roach': 'sinai', 'sinai': 'sinai'}

In [8]:
us_copy = user_sys.copy()
us_copy

{'roach': 'sinai', 'sinai': 'sinai'}

In [9]:
us_copy.pop('sinai')
us_copy

{'roach': 'sinai'}

In [10]:
help(us_copy.popitem)

Help on built-in function popitem:

popitem(...) method of builtins.dict instance
    D.popitem() -> (k, v), remove and return some (key, value) pair as a
    2-tuple; but raise KeyError if D is empty.



#### quiz

In [12]:
listA = ['className']
user_sys[listA]=1

TypeError: unhashable type: 'list'

In [13]:
user_sys[1001]=1

In [14]:
tupleA=(123)
user_sys[tupleA]=1

In [15]:
user_sys

{'roach': 'sinai', 1001: 1, 123: 1, 'sinai': 'sinai'}

In [16]:
us_copy

{'roach': 'sinai'}

In [17]:
us_copy['roach']='roach'
user_sys

{'roach': 'sinai', 1001: 1, 123: 1, 'sinai': 'sinai'}

In [18]:
us_copy

{'roach': 'roach'}

In [19]:
us_2copy = dict(us_copy)

In [20]:
us_2copy['roach']='sinai'
us_copy

{'roach': 'roach'}

In [21]:
sorted(set('You need Python.'))[2]

'P'

In [22]:
sorted(set('You need Python.'))

[' ', '.', 'P', 'Y', 'd', 'e', 'h', 'n', 'o', 't', 'u', 'y']

In [23]:
a = {1, 2, 3, 4}

b = {2, 3, 5, 6}

a.intersection(b) == a & b

True

In [81]:
import numpy as np
a = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
a.shape

(3, 3)

In [82]:
a[[2]]

array([[7, 8, 9]])

In [83]:
a[2]

array([7, 8, 9])

In [84]:
a[2].sum()

24

In [27]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
from pandas import Series
sa = Series(['a', 'b', 'c'], index = [0, 1, 2])
sb = Series(['a', 'b', 'c'])
sc = Series(['a', 'c', 'b'])
sa.equals(sc)

False

In [31]:
sb.equals(sa)

True

In [32]:
sa*3 + sc*2

0    aaaaa
1    bbbcc
2    cccbb
dtype: object

In [33]:
'VS' in Series(['Intellij', 'Notepad', 'IPython', 'R studio', 'VS'])

False

In [34]:
from pandas import Series, DataFrame
data = {'language': ['Java', 'PHP', 'Python', 'R', 'C#'],
            'year': [ 1995 ,  1995 , 1991   ,1993, 2000]}
frame = DataFrame(data)
frame['IDE'] = Series(['Intellij', 'Notepad', 'IPython', 'R studio', 'VS'])
'VS' in frame['IDE']

False

In [36]:
frame['IDE']

0    Intellij
1     Notepad
2     IPython
3    R studio
4          VS
Name: IDE, dtype: object

In [37]:
frame.ix[2]

language     Python
year           1991
IDE         IPython
Name: 2, dtype: object

In [38]:
frame

language  year       IDE
0     Java  1995  Intellij
1      PHP  1995   Notepad
2   Python  1991   IPython
3        R  1993  R studio
4       C#  2000        VS

In [39]:
dict1 = {'xiaoyun':88888,'xiaohong':5555555,'xiaoteng':11111,'xiaoyi':12341234,'xiaoyang':1212121}

In [49]:
listV=list(dict1.values())
listK=list(dict1.keys()) #view objects to list

In [48]:
type(listV[0])
{listK[i]:listV[i] for i in range(len(listK))}

{'xiaohong': 5555555,
 'xiaoteng': 11111,
 'xiaoyang': 1212121,
 'xiaoyi': 12341234,
 'xiaoyun': 88888}

***The objects returned by dict.keys(), dict.values() and dict.items() are view objects. They provide a dynamic view on the dictionary’s entries, which means that when the dictionary changes, the view reflects these changes.***

Dictionary views can be iterated over to yield their respective data, and support membership tests.

In [73]:
b = np.arange(10, dtype='int16')
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

In [74]:
v3 = b.view('int32')
v3

array([ 65536, 196610, 327684, 458758, 589832])

In [76]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
c2 = a[[3,1,1]]
c2

array([3, 1, 1])

In [79]:
a[:]=100
c2

array([3, 1, 1])

In [85]:
np.int64?

In [86]:
np.array((1,2,3))

array([1, 2, 3])

In [87]:
type(np.int64)

type